### ISSUE TITLE
RustFS - HTTP connection is closed prematurely

### ISSUE THREAD

**Issue by santosh-sahoo334** [rustfs/rustfs#522]
Hi Team, 

We are exploring RustFS as our Datalake for BigData processing. 
RustFS is currently hosted in AWS EKS in a t3.large machine. (2CPU, 8GiB RAM) with a single replica.
Below is the Deployment YAML Script. The deployment is backed by AWS EBS - gp3 (Default throughput-125MBPS and 3000 IOPS) in a PVC mode.  
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: datalake
spec:
  selector:
    matchLabels:
      app: rustfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
      - name: rustfs
        image: rustfs/rustfs:1.0.0-alpha.40
        # RustFS Configs and Env vairables - https://github.com/rustfs/rustfs/blob/main/docker-compose.yml
        env:
        - name: RUSTFS_CONSOLE_ENABLE
          value: "true"
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-creds
              key: rufs-access-key
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-creds
              key: rufs-secret-access-key
        - name: TOKIO_WORKER_THREADS
          value: "8" 
        # Debugging connection issues
        - name: RUST_BACKTRACE
          value: "1" 
        - name: RUSTFS_LOG_LEVEL
          value: "debug"  
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "2"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rustfs-pvc-dynamic-gp3
```
We are running Apache Spark workloads daily and Spark Jobs read/write to RustFS. Data is partitioned by date. 
Total Source Data Volume around - 3-5 GiB ( Subjected to grow ). 
**When the spark jobs are running, its making rustfs **in accessible** and in the logs, we see following message.** 
Apache Trino also reads these files for Dashboard queries and executes 15-16 queries concurrently. We are also getting timeout issues here. 
```
[2025-09-12 07:47:29.847994 +00:00] WARN [rustfs::server::http] [rustfs/src/server/http.rs:432] [tokio-runtime-worker:ThreadId(822)] The HTTP connection is closed prematurely and the message is not completed:connection closed before message completed
```
From the logs, its not clear what's going wrong even though Debug level is enabled. When we restart the pod, it starts working again. 

We also observed the key metrics from EBS Monitoring, nothing seems to be suspicious. Attached is the reference. 

<img width="1051" height="456" alt="Image" src="https://github.com/user-attachments/assets/97ecfe4e-ff41-411c-be09-fd828baccce1" />

<img width="1018" height="408" alt="Image" src="https://github.com/user-attachments/assets/5c2e3e98-e284-47aa-bc59-ccc607c4138d" />

Are there any performance tuning parameters, we should be aware of ? I inspected the RustFS doc, but could not find any.

**Comment by loverustfs** [comment]
Have you updated to alpha.52?

**Comment by santosh-sahoo334** [comment]
@loverustfs Not yet. Let me give it a try. Thank you!

**Comment by santosh-sahoo334** [comment]
@loverustfs I installed alpha.52. Got into another problem. Now while Spark tries to read files from RustFS, it throws below exception which I was not getting the previous version - alpha.40

```
File "/tmp/spark-files/PySpark-ETL-test.py", line 141, in <module>
    main()
  File "/tmp/spark-files/PySpark-ETL-test.py", line 60, in main
    df = spark.read.parquet("s3a://test/raw-billing-cor-data/cur2/123456789/cid-cur2/data/BILLING_PERIOD=2025-08/*.parquet")
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o93.parquet.
: org.apache.hadoop.fs.s3a.AWSBadRequestException: listStatus on s3a://test/raw-billing-cor-data/cur2/123456789/cid-cur2/data/BILLING_PERIOD=2025-08/: com.amazonaws.services.s3.model.AmazonS3Exception: max-keys must be between 1 and 1000 (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null:InvalidArgument: max-keys must be between 1 and 1000 (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null)
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:249)
        a
```
Also, getting some issues while deleting a file from RustFS, its says completed, but never deleted. 
```
[2025-09-12 13:15:43.734476 +00:00] ERROR [s3s::service] [/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/s3s-0.12.0-minio-preview.3/src/service.rs:108] [tokio-runtime-worker:ThreadId(26)] duration=5.001689507s res=Response { status: 500, version: HTTP/1.1, headers: {"content-type": "application/xml"}, body: Body { once: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>InternalError</Code><Message>Io error: can not get lock. please retry</Message></Error>" } }
```

Also, getting some warning messages. How to avoid this ?
```
[2025-09-12 13:16:18.035461 +00:00] WARN [rustfs_ecstore::bucket::policy_sys] [crates/ecstore/src/bucket/policy_sys.rs:29] [tokio-runtime-worker:ThreadId(57)] config get err Io(Custom { kind: Other, error: ConfigNotFound })
```

**Comment by loverustfs** [comment]
Hi @santosh-sahoo334 ,

Got it. We'll address this issue immediately.

We've identified this issue and have attempted to fix it in a version released three hours ago.

We've released a new version and are awaiting your confirmation.

**Comment by santosh-sahoo334** [comment]
@loverustfs I dont see any new image added 3 hours ago. The latest image I could see is alpha and alpha.52. Shall I try alpha ?

**Comment by loverustfs** [comment]
Test your code using: https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.53

Does it generate an error?

**Comment by loverustfs** [comment]
> [@loverustfs](https://github.com/loverustfs) I dont see any new image added 3 hours ago. The latest image I could see is alpha and alpha.52. Shall I try alpha ?

Sure, use this command to pull new image:

`docker pull rustfs/rustfs:alpha
`

**Comment by santosh-sahoo334** [comment]
@loverustfs Still the same issue. Tried with alpha.53. What exactly changed ?

**Comment by loverustfs** [comment]
Okay, we've received this bug report. I'll pass it on to my colleagues for further review.

Can you provide the alpha.53 error log?

Thank you!

**Comment by santosh-sahoo334** [comment]
@loverustfs Thank you. I see this error.
```
File "/tmp/spark-files/PySpark-ETL-test.py", line 141, in <module>
    main()
  File "/tmp/spark-files/PySpark-ETL-test.py", line 60, in main
    df = spark.read.parquet("s3a://test/raw-billing-cor-data/cur2/123456789/cid-cur2/data/BILLING_PERIOD=2025-08/*.parquet")
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o93.parquet.
: org.apache.hadoop.fs.s3a.AWSBadRequestException: listStatus on s3a://test/raw-billing-cor-data/cur2/123456789/cid-cur2/data/BILLING_PERIOD=2025-08/: com.amazonaws.services.s3.model.AmazonS3Exception: max-keys must be between 1 and 1000 (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null:InvalidArgument: max-keys must be between 1 and 1000 (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null)
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:249)
        a
```
In Spark, the default value of max-keys are set at 5000, but s3 is rejecting that.

**Comment by loverustfs** [comment]
> @loverustfs Thank you. I see this error.
> ```
> File "/tmp/spark-files/PySpark-ETL-test.py", line 141, in <module>
>     main()
>   File "/tmp/spark-files/PySpark-ETL-test.py", line 60, in main
>     df = spark.read.parquet("s3a://test/raw-billing-cor-data/cur2/123456789/cid-cur2/data/BILLING_PERIOD=2025-08/*.parquet")
>   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
>   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
>   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
>   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
> py4j.protocol.Py4JJavaError: An error occurred while calling o93.parquet.
> : org.apache.hadoop.fs.s3a.AWSBadRequestException: listStatus on s3a://test/raw-billing-cor-data/cur2/123456789/cid-cur2/data/BILLING_PERIOD=2025-08/: com.amazonaws.services.s3.model.AmazonS3Exception: max-keys must be between 1 and 1000 (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null:InvalidArgument: max-keys must be between 1 and 1000 (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null; Proxy: null)
>         at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:249)
>         a
> ```
> In Spark, the default value of max-keys are set at 5000, but s3 is rejecting that. 


Thank you very much. We'll fix it.

**Comment by loverustfs** [comment]
Hi  @santosh-sahoo334 ,

The lock bug you mentioned previously has been fixed. This hint suggests it's a new bug.

It's the max-keys parameter, which Rustfs doesn't support. We'll optimize support for the max-keys parameter.

**Comment by loverustfs** [comment]
Hi @santosh-sahoo334 ,

`Max-keys must be between 1 and 1000.
`
What is the number of keys in your code?

**Comment by santosh-sahoo334** [comment]
Hello @loverustfs Thank you for the prompt response. I managed to solve the issue with a spark config. However, there are other issues I am observing in alpha.53. I will create separate issue for this. 

Thanks for the help and support. Appreciate!

**Comment by loverustfs** [comment]
> Hello @loverustfs Thank you for the prompt response. I managed to solve the issue with a spark config. However, there are other issues I am observing in alpha.53. I will create separate issue for this. 
> 
> Thanks for the help and support. Appreciate!



Ok, thank you, then I'll close this issue.
